# Generated by Django 3.2 on 2022-05-06 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_permission_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='一级菜单名称')),
                ('icon', models.CharField(blank=True, max_length=64, null=True, verbose_name='图标')),
            ],
        ),
        migrations.AddField(
            model_name='permission',
            name='menu',
            field=models.ForeignKey(help_text='null表示不是菜单，否则代表二级菜单', null=True, on_delete=django.db.models.deletion.CASCADE, to='rbac.menu', verbose_name='所属的一级菜单'),
        ),
    ]
