# Generated by Django 3.2 on 2022-05-07 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20220506_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='pid',
            field=models.ForeignKey(help_text='该权限不是菜单，关联一个权限', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='rbac.permission', verbose_name='关联的权限'),
        ),
    ]
