# Generated by Django 3.2 on 2022-05-09 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_alter_permission_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='icon',
            field=models.CharField(max_length=64, verbose_name='图标'),
        ),
    ]
